name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check-out Code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v -coverprofile=profile.cov ./...

      - name: Send Test Coverage
        uses: shogo82148/actions-goveralls@v1
        with:
          path-to-profile: profile.cov
